#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "rubygrammar.h"
#include "rubyprinter.h"

#define VERSION_MAJOR			0
#define VERSION_MINOR			1

#define RUBY_HELPER_SCRIPT		"helper.rb"

extern int yyparse();
extern void push_indent(int);
extern FILE * yyin;
FILE * outscript;

int check_for_stdin(void);
void print_ruby_header(FILE * f, char * filename);

int main (int argc, char ** argv)
{
	char filename[255];
	FILE * inscript;
	int name_length; 

	filename[0] = '\0';
	if(argc > 1)
	{
		if(strncmp(argv[1], "--help", 6) == 0 ||
		   strncmp(argv[1], "-h", 2) == 0 ||
		   strncmp(argv[1] , "-v", 2) == 0)
			goto help;
		strncpy(filename, argv[1], 252);
		filename[252] = '\0';
	}
	else if(argc > 2)
	{
help:
		printf("./py2rb [file]\n"
			"\tfile is the python script or just use stdin\n"
			"\toutput script is out.rb or ends in .rb\n");
		exit(0);
	}
	if(!check_for_stdin())
	{
		if(filename[0] == '\0')
			goto help;
		inscript = fopen(filename, "r");
		if(!inscript)
		{
			printf("Can't open file \"%s\", quitting\n", filename);
			exit(-1);
		}
		yyin = inscript;
	
		name_length = strlen(filename);
		if(filename[name_length - 1] == 'y' && filename[name_length - 2] == 'p'
			&& filename[name_length - 3] == '.')
		{
			filename[name_length - 2] = 'r';
			filename[name_length - 1] = 'b';
		}
		else
		{
			filename[name_length] = '.';
			filename[name_length + 1] = 'r';
			filename[name_length + 2] = 'b';
		}
	}
	else
	{
		sprintf(filename, "out.rb");
	}

	outscript = fopen(filename, "w");
	/* FIXME I think we want to make sure we don't
	 * overwrite an existing file with this name,
	 * here and below */
	if(!outscript)
	{
		printf("Can't create output file \"%s\", quitting\n", filename);
		exit(-1);
	}
	init_ruby_grammar();
	print_ruby_header(outscript, filename);
	push_indent(0);	
	yyparse();
	ruby_grammar_process();
	ruby_print(PRINT_MAIN_PARSETREE);
	return 0;
}

int check_for_stdin(void)
{
	fd_set readfds;
	struct timeval tv;

	FD_ZERO(&readfds);
	FD_SET(fileno(stdin), &readfds);

	tv.tv_sec = 0;
	tv.tv_usec = 10;

	select(16, &readfds, 0, 0, &tv);
	if(FD_ISSET(fileno(stdin), &readfds) != 0)
		return 1;
	else
		return 0;
}

void print_ruby_header(FILE * f, char * filename)
{
	char path_to_ruby[] = "/usr/bin/ruby";
	char * syscommand;

	fprintf(f, "#!");
	fprintf(f, path_to_ruby);
	fprintf(f, "\n");
	fprintf(f, "# Generated by py2rb v%u.%u on ", VERSION_MAJOR, VERSION_MINOR);
	syscommand = malloc(strlen(filename) + 9);
	sprintf(syscommand, "date >> %s", filename);
	fclose(outscript);
	system(syscommand);
	free(syscommand);
	outscript = fopen(filename, "a");
	fprintf(f, "\n");
	fprintf(f, "require '%s'\n\n", RUBY_HELPER_SCRIPT);
}
